### ISSUE TITLE
freecad cannot import name 'getMaterialContainer' from 'ArchMaterial'

### ISSUE THREAD

**Issue by hongloan** [FreeCAD/FreeCAD-render#468]
Hi,

I tried the render workbench but it could not start. Here is the screenshot 
![Capture](https://github.com/user-attachments/assets/d1768d1a-2747-470b-9bcc-b12c940a328e)

I used FreeCAD with windows

**Comment by howetuft** [comment]
Hello,
What is your Render version? Can you check the workbench is up-to-date? (have a look in add-on manager)

**Comment by hongloan** [comment]
Hi, 

Here is the Render version. I tried with FreeCAD 0.21.2 it still works. It just doesn't work with FreeCAD 1.0

![Capture2](https://github.com/user-attachments/assets/6bd2fb6d-97aa-4c07-a618-d830b181a6da)

**Comment by howetuft** [comment]
"Installed version: 2022.4.0": your installed version is outdated... Can you try to update?

**Comment by hongloan** [comment]
I just did and it fixed. Thank you. I thought FreeCAD 1.0 comes with updated workbench.
