### ISSUE TITLE
No module named 'PySide.QtWidgets'

### ISSUE THREAD

**Issue by AlemSnyder** [FreeCAD/FreeCAD-render#415]
When trying to use the render plugin I get the above error.

```
15:16:48  No module named 'PySide.QtWidgets'
15:16:48  Traceback (most recent call last):
  File "<string>", line 107, in Initialize
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alem/.local/share/FreeCAD/Mod/Assembly4/./Render/__init__.py", line 83, in <module>
    from Render.commands import RENDER_COMMANDS  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alem/.local/share/FreeCAD/Mod/Assembly4/./Render/commands.py", line 56, in <module>
    from Render.subcontainer import start_help
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alem/.local/share/FreeCAD/Mod/Assembly4/./Render/subcontainer.py", line 68, in <module>
    from PySide.QtWidgets import QWidget, QLabel
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I know I have PySide2 installed. It is a dependency of FreeCAD which has no other issues.

```
apt search python3-pyside2.qtgui
python3-pyside2.qtgui/stable,now 5.15.8-2+b1 amd64 [installed]
  Python bindings for Qt5 Gui module (Python 3)
```

It the issue has to do with [this](https://forum.freecad.org/viewtopic.php?p=364598#p364598):

"PySide is a fake module which will import objects from PySide2. This is a trick done specifically in FreeCAD to support code written with Qt4 and Qt5 seemingly"

**Comment by AlemSnyder** [comment]
I uninstalled Assembly4 and same issue.

```
18:09:04  No module named 'PySide.QtWidgets'
18:09:04  Traceback (most recent call last):
  File "<string>", line 107, in Initialize
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alem/.local/share/FreeCAD/Mod/Render/./Render/__init__.py", line 83, in <module>
    from Render.commands import RENDER_COMMANDS  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alem/.local/share/FreeCAD/Mod/Render/./Render/commands.py", line 56, in <module>
    from Render.subcontainer import start_help
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alem/.local/share/FreeCAD/Mod/Render/./Render/subcontainer.py", line 68, in <module>
    from PySide.QtWidgets import QWidget, QLabel
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by howetuft** [comment]
Hello,
What are your FreeCAD version and your Render version?
What happens if you enter `import PySide.QtWidgets` in FreeCAD console?

**Comment by AlemSnyder** [comment]
FreeCAD version 0.20.2
Render version 2024.6.5

Some relevant console output:

```Python
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type 'help', 'copyright', 'credits' or 'license' for more information.
>>> Gui.runCommand('Std_Workbench',20)
>>> Gui.runCommand('Std_ViewStatusBar',1)
>>> import PySide
>>> import PySide.QtWidgets
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'PySide.QtWidgets'
>>> from PySide import QtWidgets
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'QtWidgets' from 'PySide' (/usr/share/freecad/Ext/PySide/__init__.py)
>>> from PySide2 import QtWidgets
>>> import PySide2.QtWidgets
>>> 
```

**Comment by AlemSnyder** [comment]
Peculiar

```bash
$ ls /usr/share/freecad/Ext/PySide/
__init__.py  QtCore.py  QtGui.py  QtSvg.py  QtUiTools.py
$ cat /usr/share/freecad/Ext/PySide/QtGui.py 
from PySide2.QtGui import *
from PySide2.QtWidgets import *
QHeaderView.setResizeMode = QHeaderView.setSectionResizeMode
```

I added `QtWidgets.py` with the contents `from PySide2.QtWidgets import *` and it fixed the issue. This seems to be an issue with FreeCAD. I will submit an issue.

**Comment by howetuft** [comment]
> This seems to be an issue with FreeCAD. I will submit an issue.
I agree! Nota: this import works perfectly in my 0.21. May I close this issue, then?

**Comment by jduf** [comment]
I had the same problem on debian and the fix suggested by @AlemSnyder worked.
